[package]
name = "discord_rich_activity"
version = "0.3.0"
authors = ["Justinas Staskevicius <staskevicius14@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
discord-rpc-client = "^0.2"